Add use cases for developer guide v1.1
AY2021S1-CS2103T-W13-3/tp pull request #12
Opened 2020-09-21 14:53 UTC by RuiFengg

Use cases added for modules and tasks

Task: add, delete, update, presets
Module: add, delete, presets

2020-09-21 16:40 UTC, RuiFengg commented
Better to merge this after everyone updates their profile in the aboutus page

2020-09-23 12:17 UTC, khoongwk reviewed
Our profiles are done, shall we merge this PR into master?

2020-09-24 10:29 UTC, hansebastian commented on docs/DeveloperGuide.md
> +**UC09: View MyModules**
I think we are going to omit MyModules from the architecture, we will be using ModuleSchedule instead, so this use case should be _View ModuleSchedule_ instead

2020-09-24 16:32 UTC, khoongwk requested changes
I think a couple of minor edits are needed to account for cases where user enters a wrong input. Other than that, LGTM!

2020-09-24 16:32 UTC, khoongwk commented on docs/DeveloperGuide.md
Should we add in a case for invalid week specified by the user as an extension to [1]? Like week 123 or week -1. Same thing for UC03 - editing a task.

2020-09-24 16:32 UTC, khoongwk commented on docs/DeveloperGuide.md
> +3.  User selects module to add into module schedule
Perhaps we should add an extension for the case when a user inputs a module code that's not in the list? Like what you did for UC07.

2020-09-25 03:03 UTC, RuiFengg commented
Amend commit to update DG use cases with suggestions from @khoongwk

2020-09-27 05:51 UTC, hansebastian approved these changes
Looks good as a draft! But I think we will need to add more details regarding the target user profile to really narrow down our target audience.

2020-09-27 06:48 UTC, khoongwk approved these changes

2020-09-27 06:49 UTC, merged