Revenue breakdown feature
AY2021S1-CS2103T-W13-3/tp pull request #156
Opened 2020-10-16 09:29 UTC by galvinleow

Closed #121 
Fixed Merge bug as well

2020-10-16 10:00 UTC, hansebastian requested changes
Looks good! Only method naming inconsistency in BreakdownRevenueCommand class

2020-10-16 10:00 UTC, hansebastian commented on src/main/java/seedu/homerce/logic/commands/revenue/BreakdownRevenueCommand.java
> +        Map<String, Double> revenueMap = breakdownExpenses(filteredRevenueList);
I think your method naming here should be `breakdownRevenue` instead of `breakdownExpenses`

2020-10-16 10:00 UTC, hansebastian commented on src/main/java/seedu/homerce/logic/commands/revenue/BreakdownRevenueCommand.java
> +    private Map<String, Double> breakdownExpenses(List<Revenue> revenueList) {
Same here for method naming

2020-10-16 13:33 UTC, yanlynnnnn commented on src/main/java/seedu/homerce/logic/commands/expense/BreakdownExpenseCommand.java
> +     * @param year year of revenue, value > 0
Should be 'expense' instead of 'revenue' here

2020-10-18 08:16 UTC, khoongwk commented
Since we are pivoting towards combining expense, revenue and profits, we should either close this PR or continue working on combining all together in this branch @galvinleow

2020-10-23 16:55 UTC, galvinleow commented
This PR is closed without merging as the feature has been completed and integrated into another PR

2020-10-23 16:55 UTC, closed without merging