Add task attributes
AY2021S1-CS2103T-W13-3/tp pull request #42
Opened 2020-09-24 15:59 UTC by yanlynnnnn

Update ParserUtil for FixedDay, Duration and TaskName
Create Enum Class for Days
Code for FixedDay, Duration and TaskName under Task attributes

2020-09-24 17:05 UTC, khoongwk requested changes
@yanlynnnnn From the class diagram, the left word is the variable name and the right word is the type!

So taskName is a variable of type string, duration has type double, fixedDays is of type 'Days'!

Edit:
Confused by the class diagram but seems like this is the right way to do it based off the other attributes in AB3. LGTM

2020-09-24 17:26 UTC, khoongwk approved these changes

2020-09-25 03:22 UTC, RuiFengg reviewed
Small changes to be made but overall changes made so far are in line with what we discussed :smile_cat:

2020-09-25 03:22 UTC, RuiFengg commented on src/main/java/seedu/address/model/task/Duration.java
> +        return String.valueOf(value) + ((value == 1) ? " hours" : " hours");
Ternary ? should hour instead of hours

2020-09-25 03:22 UTC, RuiFengg commented on src/main/java/seedu/address/model/Days.java
> +public enum Days {
Should name the class name as Day.java

2020-09-25 03:22 UTC, RuiFengg commented on src/main/java/seedu/address/model/task/FixedDay.java
> +    public final Days day;
Refactor Days to Day

2020-09-25 03:23 UTC, RuiFengg requested changes
Small changes to be made but overall changes made so far are in line with what we discussed :smile_cat:

2020-09-28 16:16 UTC, merged