Update UG for Service functionality
AY2021S1-CS2103T-W13-3/tp pull request #62
Opened 2020-09-30 15:55 UTC by hansebastian

Added commands for services functionality to the UG in accordance with the structure. A screenshot of the example outcome has not yet been added.

Let's include a numbering system for each component in our UG, for example **Features** would be under section number 4. Hence each individual feature should be should be labelled as 4.1, 4.2, 4.3 ... and each command associated with that feature be labelled with 4.1.1, 4.1.2, 4.1.3 ...

2020-10-02 19:08 UTC, khoongwk approved these changes
LGTM. The numbering of features is good and we should stick to it.

2020-10-02 20:20 UTC, khoongwk requested changes
Thought about some improvements while doing my own UG 😅

2020-10-02 20:20 UTC, khoongwk commented on docs/UserGuide.md
> +1. Type `addsvc t/Lash Lift d/0.5 p/38' into the *Command Box*.
I think you're missing a quotation mark at the end here.

2020-10-02 20:20 UTC, khoongwk commented on docs/UserGuide.md
> +
I think we need a additional section below every "Format" to tell the user to reference the command parameters. For example:
ℹ️ | Refer to Section 4.1.1, “Service Management Command Parameters” for more detail about each parameter.
-- | --

2020-10-02 20:20 UTC, khoongwk commented on docs/UserGuide.md
> +
And replicate this 'success' for the other parts till 4.1.7 😄

2020-10-02 20:21 UTC, khoongwk commented on docs/UserGuide.md
> +
Can refer to @galvinleow 's PR for this ^.

2020-10-03 05:31 UTC, yanlynnnnn reviewed
I think you might have missed out the command summary section at the bottom, but the rest looks good.

2020-10-03 05:31 UTC, yanlynnnnn commented on docs/UserGuide.md
> +Before you dive into using the feature, you may want to have a look at the common parameter used in this feature.
Should it be 'parameters' instead of 'parameter'?

2020-10-03 05:31 UTC, yanlynnnnn commented on docs/UserGuide.md
> +|`PRICE`| The revenue received from the service. <br> <br> It must be in dollars.| E.g `5.50`
Should SERVICE_CODE be added here?

2020-10-03 08:06 UTC, khoongwk requested changes
Question regarding heading levels for command parameters

2020-10-03 08:06 UTC, khoongwk commented on docs/UserGuide.md
> +### 4.1.1 Service Management Command Parameters
4.1.1 should be on the same level as 4.1.2. Should we reduce the heading level for the commands below from #### to ### to match this?

2020-10-03 14:51 UTC, hansebastian commented
Thanks for the comments @khoongwk @yanlynnnnn , I have made the changes as requested!

2020-10-03 14:51 UTC, hansebastian commented
Thanks for the comments @khoongwk @yanlynnnnn, I have made the changes as requested!

2020-10-03 14:56 UTC, khoongwk approved these changes
LGTM 😄

2020-10-03 14:58 UTC, merged